import {Component} from '@angular/core';
import {Meta, Title} from "@angular/platform-browser";

@Component({
  selector: 'signs',
  templateUrl: './road-signs.component.html'
})
export class RoadSignsComponent {

  constructor(private meta: Meta, private titleService: Title) {
    this.titleService.setTitle('Road Signs - Cedar Driving School');
    // this.meta.updateTag({name: 'description', content: this.lessons.map(elem => elem.toLowerCase()).map(elem => elem.charAt(0).toUpperCase() + elem.slice(1)).join('. ')}, 'name=description');
  }

  roadSigns = [
    "Accompanied horses and ponies",
    "Level crossing ahead with lights and barriers",
    "Restricted headroom",
    "Series of bumps or hollows ahead",
    "School ahead",
    "Traffic cross-over ahead",
    "Crosswinds",
    "Dangerous bend ahead",
    "Dangerous bend ahead right",
    "Series of dangerous bends ahead",
    "Dangerous corner ahead",
    // "Diamond road sign dangerous corner left",
    "Dangerous corner ahead right",
    "Series of dangerous corners ahead",
    "Series of dangerous corners ahead right",
    "Dual carriageway ends",
    "Danger of falling rocks",
    "Cattle and farm animals",
    "Flagman ahead",
    "Hump or ramp",
    "Side road",
    "Crossroads with dual carriageway",
    "Crossroads major road",
    "Crossroads minor road",
    "Y-junction",
    "T-junction",
    "Crossroads",
    "T-junction with dual carriageway",
    "Side road left",
    "Side road right",
    "Loose chipping works",
    "Merge to single lane",
    "Merging traffic left",
    "Merging traffic right",
    "Merging-diverging road",
    "Mini-Roundabout ahead",
    "Offside lane (of two) closed",
    "Nearside lane (of three) closed",
    "One-lane crossover (out)",
    "One-lane crossover (back)",
    "Overhead electric cables",
    "Pedestrians cross to left",
    "Pedestrians cross to right",
    "Pedestrian crossing ahead",
    "Queues likely",
    "Start of central reserve or obstruction",
    "Sharp rise ahead",
    "Road narrows from left",
    "Road narrows from right",
    "Roadworks ahead",
    "Sharp dip ahead",
    "Sheep",
    "Single lane (for shuttle working)",
    "Site access on left",
    "Site access on right",
    "Slippery for cyclists",
    "Slippery road ahead",
    "Staggered crossroads",
    "Steep descent ahead",
    "Steep ascent ahead",
    "Tram lane crossing ahead",
    "Tunnel ahead",
    "Two-way traffic",
    "Uneven surface",
    "Level crossing ahead, unguarded by gates or lifting barrier",
    "Unprotected quay, canal or river ahead",
    "Deer or wild animals",
    "Disabled persons parking bay",
    "Entry to motorway",
    "Information road sign traffic calming",
    "Disabled Parking 1",
    "Disabled Parking 2",
    "Pedestrian Crossing",
    "Pedestrian Crossing 2",
    "Pedestrian Crossing 3",
    "Hospital sign",
    "Keep left",
    "Keep right",
    "Pass either side",
    "Straight ahead",
    "Turn right",
    "Turn left",
    "Turn left ahead",
    "Turn right ahead",
    "Cycle track",
    "Clearway",
    "No entry",
    "No right turn",
    "No left turn",
    "No overtaking",
    "Height restriction",
    "No U-turn",
    "Parking permitted",
    "Parking not permitted",
    "Taxi rank",
    "Pedestrianised zone",
    "Yield 1",
    "Yield 2",
    "Stop",
    "School wardens stop sign",
    "No entry for pedestrians",
    "Max speed limit 120kmh",
    "Max speed limit 100kmh",
    "Max speed limit 80kmh",
    "Max speed limit 60kmh",
    "Max speed limit 50kmh",
    "Max speed limit 30kmh",
    "No entry to goods vehicles",
    "Roundabout",
    "No entry to vehicles",
    "Maximum vehicle width",
    "Maximum axle weight",
    "No cycling",
    "No horse riding",
    "No horse carriages",
    "Pedestrians and bicycles only",
    "Crossroads 2",
    "Side road left 2",
    "Side road right 2",
    "T-junction right major",
    "T-junction left major",
    "Side road right major",
    "Side road left major",
    "Y-junction right major",
    "Y-junction left major",
    "Staggered crossroads 2",
    "T-junction with dual carriageway 2",
    "Merging traffic 2",
    "Merging-diverging traffic",
    "Traffic signals ahead",
    "Roundabout ahead",
    "Mini-Roundabout ahead 2",
    "Dangerous left corner ahead",
    "Dangerous right corner ahead",
    "Sharp change of direction to the left",
    "Sharp change of direction to the right",
    "Road narrows from left 2",
    "Road narrows from right 2",
    "Road narrows on both sides 2",
    "Two-way traffic 2",
    "Restricted headroom 2",
    "Restricted width",
    "Maximum axle loading weight",
    "Level crossing ahead with lights and barriers 2",
    "Level crossing ahead 2",
    "Tram lane crossing ahead 2",
    "Pedestrian crossing ahead 2",
    "School ahead 2",
    "Cyclists 2",
    "Slippery for cyclists 2",
    "Accompanied horses and ponies 2",
    "Cattle and farm animals 2",
    "Sheep 2",
    "Deer or wild animals 2",
    "Unprotected quay, canal or river ahead 2",
    "Tunnel ahead 2",
    "Danger of falling rocks 2",
    "Low flying aircraft",
    "Crosswinds 2",
    "Opening bridge warning",
    "Tractors warning",
    "Drive on left",
    "Hazard 2",
    "Barrier board",
    "Road works ahead",
    "Single lane (for shuttle working) 2",
    "Two way traffic",
    "Road narrows on left",
    "Road narrows on right",
    "Road narrows on both sides 3",
    "Side road on left",
    "Side road on right",
    "Site access on left 2",
    "Site access on right 2",
    "Temporary traffic signals",
    "Flagman ahead 2",
    "Loose chippings",
    "Soft verge",
    "Pedestrian cross to left",
    "Pedestrian cross to right",
    "Mandatory road sign gÇill sl°",
    "Mandatory road sign keep left",
    "Mandatory road sign keep right",
    "Mandatory road sign no entry",
    "Mandatory road sign no left turn",
    "Mandatory road sign no right turn",
    "Mandatory road sign no vehicles",
    "Mandatory road sign pass either side",
    "Mandatory road sign stop",
    "Mandatory road sign straight ahead",
    "Mandatory road sign turn left",
    "Mandatory road sign turn left ahead",
    "Mandatory road sign turn right",
    "Mandatory road sign turn right ahead",
    "Mandatory road sign yield",
    "Regulatory road sign clearway",
    "Regulatory road sign end zonal restriction",
    "Regulatory road sign no entry for pedestrians",
    "Regulatory road sign no entry for weight",
    "Regulatory road sign no entry to goods vehicles",
    "Regulatory road sign no overtaking",
    "Regulatory road sign no parking",
    "Regulatory road sign no u turn",
    "Regulatory road sign parking permitted",
    "Regulatory road sign pedestrianised street",
    "Regulatory road sign taxi rank",
    "Regulatory road sign zonal restriction",
    "Road sign detour ahead",
    "Road sign detour destination",
    "Road sign detour to right",
    "Road sign end detour",
    "Wild Atlantic Way Sign"
  ];


  filterString: string;
  countFilter: number = this.roadSigns.length;

  doFilterCount(filter): void {
    if(filter) {
      this.countFilter = this.roadSigns.filter(sign => sign.toLowerCase().includes(this.filterString.toLocaleLowerCase())).length;
    } else {
      this.countFilter = this.roadSigns.length;
    }
  }

}
