import {Component} from '@angular/core';
import {Meta, Title} from "@angular/platform-browser";

@Component({
  selector: 'signs',
  templateUrl: './road-signs.component.html'
})
export class RoadSignsComponent {

  constructor(private meta: Meta, private titleService: Title) {
    this.titleService.setTitle('Road Signs - Cedar Driving School');
    // this.meta.updateTag({name: 'description', content: this.lessons.map(elem => elem.toLowerCase()).map(elem => elem.charAt(0).toUpperCase() + elem.slice(1)).join('. ')}, 'name=description');
  }

  roadSigns = [
    "Accompanied horses and ponies",
    "Level crossing ahead with lights and barriers",
    "Restricted headroom",
    "Series of bumps or hollows ahead",
    "School ahead",
    "Traffic cross-over ahead",
    "Crosswinds",
    "Dangerous bend ahead",
    "Dangerous bend ahead right",
    "Series of dangerous bends ahead",
    "Dangerous corner ahead",
    // "Diamond road sign dangerous corner left",
    "Dangerous corner ahead right",
    "Series of dangerous corners ahead",
    "Series of dangerous corners ahead right",
    "Dual carriageway ends",
    "Danger of falling rocks",
    "Cattle and farm animals",
    "Flagman ahead",
    "Hump or ramp",
    "Side road",
    "Crossroads with dual carriageway",
    "Crossroads major road",
    "Crossroads minor road",
    "Y-junction",
    "T-junction",
    "Crossroads",
    "T-junction with dual carriageway",
    "Side road left",
    "Side road right",
    "Loose chipping works",
    "Merge to single lane",
    "Merging traffic left",
    "Merging traffic right",
    "Merging-diverging road",
    "Mini-Roundabout ahead",
    "Offside lane (of two) closed",
    "Nearside lane (of three) closed",
    "One-lane crossover (out)",
    "One-lane crossover (back)",
    "Overhead electric cables",
    "Pedestrians cross to left",
    "Pedestrians cross to right",
    "Pedestrian crossing ahead",
    "Queues likely",
    "Start of central reserve or obstruction",
    "Sharp rise ahead",
    "Road narrows from left",
    "Road narrows from right",
    "Roadworks ahead",
    "Sharp dip ahead",
    "Sheep",
    "Single lane (for shuttle working)",
    "Site access on left",
    "Site access on right",
    "Slippery for cyclists",
    "Slippery road ahead",
    "Staggered crossroads",
    "Steep descent ahead",
    "Steep ascent ahead",
    "Tram lane crossing ahead",
    "Tunnel ahead",
    "Two-way traffic",
    "Uneven surface",
    "Level crossing ahead, unguarded by gates or lifting barrier",
    "Unprotected quay, canal or river ahead",
    "Deer or wild animals",
    "Disabled persons parking bay",
    "Entry to motorway",
    "Information road sign traffic calming",
    "Disabled Parking 1",
    "Disabled Parking 2",
    "Pedestrian Crossing",
    "Pedestrian Crossing 2",
    "Pedestrian Crossing 3",
    "Hospital sign",
    "Keep left",
    "Keep right",
    "Pass either side",
    "Straight ahead",
    "Turn right",
    "Turn left",
    "Turn left ahead",
    "Turn right ahead",
    "Cycle track",
    "Clearway",
    "No entry",
    "No right turn",
    "No left turn",
    "No overtaking",
    "Height restriction",
    "No U-turn",
    "Parking permitted",
    "Parking not permitted",
    "Taxi rank",
    "Pedestrianised zone",
    "Yield 1",
    "Yield 2",
    "Stop",
    "School wardens stop sign",
    "No entry for pedestrians",
    "Max speed limit 120kmh",
    "Max speed limit 100kmh",
    "Max speed limit 80kmh",
    "Max speed limit 60kmh",
    "Max speed limit 50kmh",
    "Max speed limit 30kmh",
    "No entry to goods vehicles",
    "Roundabout",
    "No entry to vehicles",
    "Maximum vehicle width",
    "Maximum axle weight",
    "No cycling",
    "No horse riding",
    "No horse carriages",
    "Pedestrians and bicycles only",
    "Crossroads 2",
    "Side road left 2",
    "Side road right 2",
    "T-junction right major",
    "T-junction left major",
    "Side road right major",
    "Side road left major",
    "Y-junction right major",
    "Y-junction left major",
    "Staggered crossroads 2",
    "T-junction with dual carriageway 2",
    "Merging traffic 2",
    "Merging-diverging traffic",
    "Ireland road sign W 042",
    "Ireland road sign W 043",
    "Ireland road sign W 044",
    "Ireland road sign W 050L",
    "Ireland road sign W 050R",
    "Ireland road sign W 061L",
    "Ireland road sign W 061R",
    "Ireland road sign W 062L",
    "Ireland road sign W 062R",
    "Ireland road sign W 063L",
    "Ireland road sign W 063R",
    "Ireland road sign W 070L",
    "Ireland road sign W 070R",
    "Ireland road sign W 071",
    "Ireland road sign W 080",
    "Ireland road sign W 081",
    "Ireland road sign W 101",
    "Ireland road sign W 102",
    "Ireland road sign W 110",
    "Ireland road sign W 113",
    "Ireland road sign W 115",
    "Ireland road sign W 116",
    "Ireland road sign W 117",
    "Ireland road sign W 120",
    "Ireland road sign W 121",
    "Ireland road sign W 124",
    "Ireland road sign W 140",
    "Ireland road sign W 141",
    "Ireland road sign W 143",
    "Ireland road sign W 144",
    "Ireland road sign W 150",
    "Ireland road sign W 151",
    "Ireland road sign W 152",
    "Ireland road sign W 153",
    "Ireland road sign W 160",
    "Ireland road sign W 162",
    "Ireland road sign W 164",
    "Ireland road sign W 165",
    "Ireland road sign W 166",
    "Ireland road sign W 167",
    "Ireland road sign W 168",
    "Ireland road sign W 169",
    "Ireland road sign W 170",
    "Ireland road sign W 183",
    "Ireland road sign W 184",
    "Ireland road sign W 185",
    "Ireland road sign WK 001",
    "Ireland road sign WK 030",
    "Ireland road sign WK 031",
    "Ireland road sign WK 032",
    "Ireland road sign WK 033",
    "Ireland road sign WK 034",
    "Ireland road sign WK 050",
    "Ireland road sign WK 051",
    "Ireland road sign WK 052",
    "Ireland road sign WK 053",
    "Ireland road sign WK 060",
    "Ireland road sign WK 061",
    "Ireland road sign WK 073",
    "Ireland road sign WK 074",
    "Ireland road sign WK 080",
    "Ireland road sign WK 081",
    "Ireland road sign WK 143",
    "Ireland road sign WK 144",
    "Ireland road sign 105",
    "Ireland road sign 106L",
    "Ireland road sign 106R",
    "Ireland road sign 107",
    "Ireland road sign 113LR",
    "Ireland road sign 113RL",
    "Ireland road sign 127",
    "Mandatory road sign gÇill sl°",
    "Mandatory road sign keep left",
    "Mandatory road sign keep right",
    "Mandatory road sign no entry",
    "Mandatory road sign no left turn",
    "Mandatory road sign no right turn",
    "Mandatory road sign no vehicles",
    "Mandatory road sign pass either side",
    "Mandatory road sign stop",
    "Mandatory road sign straight ahead",
    "Mandatory road sign turn left",
    "Mandatory road sign turn left ahead",
    "Mandatory road sign turn right",
    "Mandatory road sign turn right ahead",
    "Mandatory road sign yield",
    "Regulatory road sign clearway",
    "Regulatory road sign end zonal restriction",
    "Regulatory road sign no entry for pedestrians",
    "Regulatory road sign no entry for weight",
    "Regulatory road sign no entry to goods vehicles",
    "Regulatory road sign no overtaking",
    "Regulatory road sign no parking",
    "Regulatory road sign no u turn",
    "Regulatory road sign parking permitted",
    "Regulatory road sign pedestrianised street",
    "Regulatory road sign taxi rank",
    "Regulatory road sign zonal restriction",
    "Road sign detour ahead",
    "Road sign detour destination",
    "Road sign detour to right",
    "Road sign end detour",
    "Wild Atlantic Way Sign"
  ]


  filterString: string;
  countFilter: number = this.roadSigns.length;

  doFilterCount(filter): void {
    if(filter) {
      this.countFilter = this.roadSigns.filter(sign => sign.toLowerCase().includes(this.filterString.toLocaleLowerCase())).length;
    } else {
      this.countFilter = this.roadSigns.length;
    }
  }

}
