import {Component} from '@angular/core';
import {Meta, Title} from "@angular/platform-browser";

@Component({
  selector: 'signs',
  templateUrl: './road-signs.component.html'
})
export class RoadSignsComponent {

  constructor(private meta: Meta, private titleService: Title) {
    this.titleService.setTitle('Road Signs - Cedar Driving School');
    // this.meta.updateTag({name: 'description', content: this.lessons.map(elem => elem.toLowerCase()).map(elem => elem.charAt(0).toUpperCase() + elem.slice(1)).join('. ')}, 'name=description');
  }

  roadSigns = [
    "Accompanied horses and ponies",
    "Level crossing ahead with lights and barriers",
    "Restricted headroom",
    "Series of bumps or hollows ahead",
    "School ahead",
    "Traffic cross-over ahead",
    "Crosswinds",
    "Dangerous bend ahead",
    "Dangerous bend ahead right",
    "Series of dangerous bends ahead",
    "Dangerous corner ahead",
    // "Diamond road sign dangerous corner left",
    "Dangerous corner ahead right",
    "Series of dangerous corners ahead",
    "Series of dangerous corners ahead right",
    "Dual carriageway ends",
    "Danger of falling rocks",
    "Diamond road sign farm animals",
    "Diamond road sign flagman ahead",
    "Diamond road sign hump works",
    "Diamond road sign junction",
    "Diamond road sign junction across dual carriageway",
    "Diamond road sign junction across major road",
    "Diamond road sign junction across minor road",
    "Diamond road sign junction bend minor road",
    "Diamond road sign junction bend minor road left",
    "Diamond road sign junction corner minor road",
    "Diamond road sign junction corner minor road left",
    "Diamond road sign junction crossroads",
    "Diamond road sign junction dual carriageway",
    "Diamond road sign junction left works",
    "Diamond road sign junction minor road",
    "Diamond road sign junction minor road right",
    "Diamond road sign junction right",
    "Diamond road sign junction right works",
    "Diamond road sign lane splits",
    "Diamond road sign loose chipping works",
    "Diamond road sign low flying aircraft",
    "Diamond road sign merge to single lane",
    "Diamond road sign merging traffic left",
    "Diamond road sign merging traffic right",
    "Diamond road sign merging-diverging road",
    "Diamond road sign mini-roundabout",
    "Diamond road sign offside lane closed",
    "Diamond road sign offside lane closed of 3",
    "Diamond road sign one-lane crossover",
    "Diamond road sign one-lane crossover back",
    "Diamond road sign overhead electic cables",
    "Diamond road sign overhead electric cables works",
    "Diamond road sign pedestrian cross to left",
    "Diamond road sign pedestrian cross to right",
    "Diamond road sign pedestrian crossing ahead",
    "Diamond road sign queues",
    "Diamond road sign road divides",
    "Diamond road sign road hump",
    "Diamond road sign road narrow left",
    "Diamond road sign road narrow left works",
    "Diamond road sign road narrow right",
    "Diamond road sign road narrow right works",
    // "Diamond road sign road narrows",
    "Diamond road sign road narrows works",
    "Diamond road sign roadworks",
    "Diamond road sign roundabout",
    "Diamond road sign sharp depression",
    "Diamond road sign sheeps",
    "Diamond road sign single lane",
    "Diamond road sign single lane works",
    "Diamond road sign site access on left",
    "Diamond road sign site access on right",
    "Diamond road sign slippery for cyclists",
    "Diamond road sign slippery surface",
    "Diamond road sign slippery surface works",
    "Diamond road sign staggered junction equal roads",
    "Diamond road sign staggered junction minor roads",
    "Diamond road sign steep decline",
    "Diamond road sign steep incline",
    "Diamond road sign T junction",
    "Diamond road sign T junction major road",
    "Diamond road sign Tram lane crossing ahead",
    "Diamond road sign tunnel",
    "Diamond road sign two-way traffic lanes",
    "Diamond road sign uneven surface",
    "Diamond road sign unguarded crossing",
    "Diamond road sign unprotected quay",
    "Diamond road sign wild animals",
    "Diamond road sign Y junction",
    "Information road sign disabled persons parking",
    "Information road sign motorway",
    "Information road sign traffic calming",
    "Ireland road sign - Disabled Parking 1",
    "Ireland road sign - Disabled Parking 2",
    "Ireland road sign - Pedestrian Crossing",
    "Ireland road sign - Pedestrian Crossing 2",
    "Ireland road sign - Pedestrian Crossing 3",
    "Ireland road sign F 210",
    "Ireland road sign F 350 (old)",
    "Ireland road sign RUS 001",
    "Ireland road sign RUS 001 (old)",
    "Ireland road sign RUS 002",
    "Ireland road sign RUS 002 (old)",
    "Ireland road sign RUS 003",
    "Ireland road sign RUS 004",
    "Ireland road sign RUS 004 (old)",
    "Ireland road sign RUS 005",
    "Ireland road sign RUS 005 (old)",
    "Ireland road sign RUS 006",
    "Ireland road sign RUS 006 (old)",
    "Ireland road sign RUS 007",
    "Ireland road sign RUS 008",
    "Ireland road sign RUS 009",
    "Ireland road sign RUS 009 (old)",
    "Ireland road sign RUS 010",
    "Ireland road sign RUS 011",
    "Ireland road sign RUS 012",
    "Ireland road sign RUS 013",
    "Ireland road sign RUS 013 (old)",
    "Ireland road sign RUS 014",
    "Ireland road sign RUS 014 (HVs)",
    "Ireland road sign RUS 016",
    "Ireland road sign RUS 016 (old)",
    "Ireland road sign RUS 017",
    "Ireland road sign RUS 017 (left)",
    "Ireland road sign RUS 018",
    "Ireland road sign RUS 018L",
    "Ireland road sign RUS 018LR",
    "Ireland road sign RUS 018R",
    "Ireland road sign RUS 019",
    "Ireland road sign RUS 019L",
    "Ireland road sign RUS 019LR",
    "Ireland road sign RUS 019R",
    "Ireland road sign RUS 020L",
    "Ireland road sign RUS 020LR",
    "Ireland road sign RUS 020R",
    "Ireland road sign RUS 021",
    "Ireland road sign RUS 025",
    "Ireland road sign RUS 026 (English)",
    "Ireland road sign RUS 026 (Gaeilge)",
    "Ireland road sign RUS 026 (old)",
    "Ireland road sign RUS 027",
    "Ireland road sign RUS 032",
    "Ireland road sign RUS 038",
    "Ireland road sign RUS 039",
    "Ireland road sign RUS 040",
    "Ireland road sign RUS 041",
    "Ireland road sign RUS 042",
    "Ireland road sign RUS 043",
    "Ireland road sign RUS 044",
    "Ireland road sign RUS 046",
    "Ireland road sign RUS 046 (old)",
    "Ireland road sign RUS 049",
    "Ireland road sign RUS 050",
    "Ireland road sign RUS 052",
    "Ireland road sign RUS 053",
    "Ireland road sign RUS 054",
    "Ireland road sign RUS 055",
    "Ireland road sign RUS 055 (old)",
    "Ireland road sign RUS 056",
    "Ireland road sign RUS 057",
    "Ireland road sign RUS 058",
    "Ireland road sign RUS 062",
    "Ireland road sign W 001",
    "Ireland road sign W 002L",
    "Ireland road sign W 002R",
    "Ireland road sign W 003L",
    "Ireland road sign W 003R",
    "Ireland road sign W 004L",
    "Ireland road sign W 004R",
    "Ireland road sign W 005L",
    "Ireland road sign W 005R",
    "Ireland road sign W 006L",
    "Ireland road sign W 006R",
    "Ireland road sign W 007LR",
    "Ireland road sign W 007RL",
    "Ireland road sign W 008L",
    "Ireland road sign W 008R",
    "Ireland road sign W 012L",
    "Ireland road sign W 012R",
    "Ireland road sign W 013",
    "Ireland road sign W 014",
    "Ireland road sign W 015",
    "Ireland road sign W 016",
    "Ireland road sign W 017L",
    "Ireland road sign W 017R",
    "Ireland road sign W 018L",
    "Ireland road sign W 018R",
    "Ireland road sign W 019",
    "Ireland road sign W 020",
    "Ireland road sign W 021L",
    "Ireland road sign W 021R",
    "Ireland road sign W 022",
    "Ireland road sign W 030",
    "Ireland road sign W 031",
    "Ireland road sign W 032",
    "Ireland road sign W 040",
    "Ireland road sign W 041",
    "Ireland road sign W 042",
    "Ireland road sign W 043",
    "Ireland road sign W 044",
    "Ireland road sign W 050L",
    "Ireland road sign W 050R",
    "Ireland road sign W 061L",
    "Ireland road sign W 061R",
    "Ireland road sign W 062L",
    "Ireland road sign W 062R",
    "Ireland road sign W 063L",
    "Ireland road sign W 063R",
    "Ireland road sign W 070L",
    "Ireland road sign W 070R",
    "Ireland road sign W 071",
    "Ireland road sign W 071 (old)",
    "Ireland road sign W 080",
    "Ireland road sign W 081",
    "Ireland road sign W 101",
    "Ireland road sign W 102",
    "Ireland road sign W 105 (old)",
    "Ireland road sign W 106 (old)",
    "Ireland road sign W 110",
    "Ireland road sign W 113",
    "Ireland road sign W 115",
    "Ireland road sign W 116",
    "Ireland road sign W 117",
    "Ireland road sign W 120",
    "Ireland road sign W 121",
    "Ireland road sign W 124",
    "Ireland road sign W 140",
    "Ireland road sign W 141",
    "Ireland road sign W 143",
    "Ireland road sign W 144",
    "Ireland road sign W 150",
    "Ireland road sign W 151",
    "Ireland road sign W 152",
    "Ireland road sign W 153",
    "Ireland road sign W 160",
    "Ireland road sign W 162",
    "Ireland road sign W 164",
    "Ireland road sign W 165",
    "Ireland road sign W 166",
    "Ireland road sign W 167",
    "Ireland road sign W 168",
    "Ireland road sign W 169",
    "Ireland road sign W 170",
    "Ireland road sign W 183",
    "Ireland road sign W 184",
    "Ireland road sign W 185",
    "Ireland road sign WK 001",
    "Ireland road sign WK 030",
    "Ireland road sign WK 031",
    "Ireland road sign WK 032",
    "Ireland road sign WK 033",
    "Ireland road sign WK 034",
    "Ireland road sign WK 050",
    "Ireland road sign WK 051",
    "Ireland road sign WK 052",
    "Ireland road sign WK 053",
    "Ireland road sign WK 060",
    "Ireland road sign WK 061",
    "Ireland road sign WK 073",
    "Ireland road sign WK 074",
    "Ireland road sign WK 080",
    "Ireland road sign WK 081",
    "Ireland road sign WK 143",
    "Ireland road sign WK 144",
    "Ireland road sign 105",
    "Ireland road sign 106L",
    "Ireland road sign 106R",
    "Ireland road sign 107",
    "Ireland road sign 113LR",
    "Ireland road sign 113RL",
    "Ireland road sign 127",
    "Mandatory road sign gÇill sl°",
    "Mandatory road sign keep left",
    "Mandatory road sign keep right",
    "Mandatory road sign no entry",
    "Mandatory road sign no left turn",
    "Mandatory road sign no right turn",
    "Mandatory road sign no vehicles",
    "Mandatory road sign pass either side",
    "Mandatory road sign stop",
    "Mandatory road sign straight ahead",
    "Mandatory road sign turn left",
    "Mandatory road sign turn left ahead",
    "Mandatory road sign turn right",
    "Mandatory road sign turn right ahead",
    "Mandatory road sign yield",
    "Regulatory road sign clearway",
    "Regulatory road sign end zonal restriction",
    "Regulatory road sign no entry for pedestrians",
    "Regulatory road sign no entry for weight",
    "Regulatory road sign no entry to goods vehicles",
    "Regulatory road sign no overtaking",
    "Regulatory road sign no parking",
    "Regulatory road sign no u turn",
    "Regulatory road sign parking permitted",
    "Regulatory road sign pedestrianised street",
    "Regulatory road sign taxi rank",
    "Regulatory road sign zonal restriction",
    "Road sign detour ahead",
    "Road sign detour destination",
    "Road sign detour to right",
    "Road sign end detour",
    "Wild Atlantic Way Sign"
  ]


  filterString: string;
  countFilter: number = this.roadSigns.length;

  doFilterCount(filter): void {
    if(filter) {
      this.countFilter = this.roadSigns.filter(sign => sign.toLowerCase().includes(this.filterString.toLocaleLowerCase())).length;
    } else {
      this.countFilter = this.roadSigns.length;
    }
  }

}
